-- CreateTable
CREATE TABLE "User" (
    id TEXT NOT NULL PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    createdAt TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CreateTable
CREATE TABLE "Goal" (
    id TEXT NOT NULL PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    type TEXT NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT false,
    startDate TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    endDate TIMESTAMP(3),
    userId TEXT NOT NULL,
    createdAt TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT Goal_userId_fkey FOREIGN KEY (userId) REFERENCES "User" (id) ON DELETE CASCADE ON UPDATE CASCADE
);
